version: 2

sources:
  - name: staging
    database: de-zoomcamp-360309
    schema: trips_data_all_us

    tables:
      - name: green_tripdata_paritioned
      - name: yellow_tripdata_paritioned

models:
  - name: stg_green_tripdata
    description:
    columns:
    